# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "thunderbolt" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-bd07ac5f-3f1a-4cea-9f2e-fa9a76a710d3";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-bd07ac5f-3f1a-4cea-9f2e-fa9a76a710d3".device = "/dev/disk/by-uuid/bd07ac5f-3f1a-4cea-9f2e-fa9a76a710d3";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2802-A078";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
